// <copyright file="PostFundingCaseCreate.cs" company="Department of Justice/ministaire de la Justice">
// Copyright (c) 2015 All Rights Reserved
// </copyright>
// <author>Department of Justice/ministaire de la Justice</author>
// <date>9/3/2015 2:16:50 PM</date>
// <summary>Implements the PostFundingCaseCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace CrmGC.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using Microsoft.Xrm.Sdk.Client;

    /// <summary>
    /// PostFundingCaseCreate Plugin.
    /// </summary>    
    public class PostFundingCaseCreate: IPlugin
    {
        /// <summary>
        /// A plug-in that creates a follow-up task activity when a new account is created.
        /// </summary>
        /// <remarks>Register this plug-in on the Create message, account entity,
        /// and asynchronous mode.
        /// </remarks>
        public void Execute(IServiceProvider serviceProvider)
        {
            //Extract the tracing service for use in debugging sandboxed plug-ins.
            ITracingService tracingService =
                (ITracingService)serviceProvider.GetService(typeof(ITracingService));

            // Obtain the execution context from the service provider.
            IPluginExecutionContext context = (IPluginExecutionContext)
                serviceProvider.GetService(typeof(IPluginExecutionContext));

            // The InputParameters collection contains all the data passed in the message request.
            if (context.InputParameters.Contains("Target") &&
                context.InputParameters["Target"] is Entity)
            {

                // Obtain the target entity from the input parameters.
                Entity entity = (Entity)context.InputParameters["Target"];

                if (entity.LogicalName != "gcbase_fundingcase")
                    return;                
                
                //FaultException ex1 = new FaultException();
                //throw new InvalidPluginExecutionException("test", ex1);
              

                try
                {
                    //fundCentreBudget["gcbase_name"] = param.name + "-" + fy.Value;
                    //// ctx.Attach(fundCentreBudget)
                    //ctx.AddObject(fundCentreBudget);
                    //ctx.SaveChanges();
                   
                   

                    if (entity.Attributes.Contains("gcbase_amountsbyfiscalyearserver"))
                    {

                        char[] delimitedChar = { ';' };
                        
                        Entity fundingAmountByFY = new Entity("gcbase_fundingcaseamountbyfy");
                        string[] yearlyAmounts = entity.Attributes["gcbase_amountsbyfiscalyearserver"].ToString().Split(delimitedChar);
                        foreach (string ya in yearlyAmounts)
                        {

                            fundingAmountByFY["gcbase_fundingcase"] = new EntityReference("gcbase_fundingcase", entity.Id);
                            //fys[index] = (string)Enum.GetName(typeof(goal_fiscalyear), year);
                            OptionSetValue fy = new OptionSetValue();
                            var indexForFY = ya.IndexOf("Y");
                            var indexForAmount = ya.IndexOf("-");
                            var yearStr = ya.Substring(indexForFY + 1,4);
                            var amountStr = ya.Substring(indexForAmount + 1);
                            tracingService.Trace("year is:" + yearStr);
                            tracingService.Trace("amount is:" + amountStr);
                            Money amount = new Money(decimal.Parse(amountStr));
                            fy.Value = Int32.Parse(yearStr);
                            fundingAmountByFY["gcbase_fiscalyear"] = fy;
                            fundingAmountByFY["gcbase_amount"] = amount;

                            //// Obtain the organization service reference.
                            IOrganizationServiceFactory serviceFactory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
                            IOrganizationService service = serviceFactory.CreateOrganizationService(context.UserId);

                            //// Create the task in Microsoft Dynamics CRM.
                            tracingService.Trace("FollowupPlugin: Creating the budget item.");
                            service.Create(fundingAmountByFY);

                            tracingService.Trace(ya);
                        }
                        //throw new InvalidPluginExecutionException(entity.Attributes["gcbase_amountsbyfiscalyearserver"].ToString(), ex1);


                       
                        
                       
                    
                    }
                    //// Create a task activity to follow up with the account customer in 7 days. 
                    
                    
                    //Entity followup = new Entity("task");

                    //followup["subject"] = "Send e-mail to the new customer.";
                    //followup["description"] =
                    //    "Follow up with the customer. Check if there are any new issues that need resolution.";
                    //followup["scheduledstart"] = DateTime.Now.AddDays(7);
                    //followup["scheduledend"] = DateTime.Now.AddDays(7);
                    //followup["category"] = context.PrimaryEntityName;

                    //// Refer to the account in the task activity.
                    //if (context.OutputParameters.Contains("id"))
                    //{
                    //    Guid regardingobjectid = new Guid(context.OutputParameters["id"].ToString());
                    //    string regardingobjectidType = "account";

                    //    followup["regardingobjectid"] =
                    //    new EntityReference(regardingobjectidType, regardingobjectid);
                    //}

                    //// Obtain the organization service reference.
                    //IOrganizationServiceFactory serviceFactory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
                    //IOrganizationService service = serviceFactory.CreateOrganizationService(context.UserId);

                    //// Create the task in Microsoft Dynamics CRM.
                    //tracingService.Trace("FollowupPlugin: Creating the task activity.");
                    //service.Create(followup);
                }
                catch (FaultException<OrganizationServiceFault> ex)
                {
                    throw new InvalidPluginExecutionException("An error occurred in the FollowupPlugin plug-in.", ex);
                }

                catch (Exception ex)
                {
                    tracingService.Trace("FollowupPlugin: {0}", ex.ToString());
                    throw;
                }
            }
        }
    }
}
